### ISSUE TITLE
Py Script edit use at compile too many storage

### ISSUE THREAD

**Issue by sinus23** [FYSETC/Bootloader-STM32F103#1]
U can deaktivate all functions 
fysetc_STM32F1\firmware.elf section `.rodata' wil
l not fit in region `rom'

for define in env['CPPDEFINES']:
    if define[0] == "VECT_TAB_ADDR":
        env['CPPDEFINES'].remove(define)
env['CPPDEFINES'].append(("VECT_TAB_ADDR", "0x08010000"))
env.Replace(LDSCRIPT_PATH="buildroot/share/PlatformIO/ldscripts/fysetc_aio_ii.ld")

**Comment by GiliFuuu** [comment]
Following is the compile result of boot loader.
![image](https://user-images.githubusercontent.com/54924249/64930320-6b4b4380-d862-11e9-8f33-62ea19e7bace.png)
You can change 0x08010000 to a lower address like 0x0800c000 to save the flash , but you also need to change the flash address in the this boot loader too.

**Comment by GerogeFu** [comment]
README updated, follow it. Thanks for this post.
